#' Simulate follow-up for contact tracing data
#' 
#' This function adds simulated follow-up to a `ctdata` object as generated by 
#' [make_ctdata()] or simulated via [sim_ctdata()]. The function simulates
#' follow-up for each individual in the `ctdata` object, based on the specified
#' follow-up time and the probability of being followed up. The function returns
#' a modified `ctdata` object with the simulated follow-up data added.
#' 
#' @author Thibaut Jombart
#' 
#' @export
#' 
#' @seealso [make_ctdata()] to create contact tracing data from existing data, 
#' or [sim_ctdata()] to simulate them
#' 
#' @param x a `ctdata` object
#' 
#' @param coverage the expected proportion of contacts visited at any time step; defaults 
#'   to 0 - no follow-up
#' 
#' @param time an `integer` indicating the number of days to run the simulation 
#'   for; starts from the most recent date in `x`, be it in follow-up 
#'   history or in exposures; defaults to 1 day
#'   
#' @param delay an `integer` the minimum delay for follow-up to start, after the
#'   first exposure of the concerned contact; defaults to 1 - visit can start
#'   the day after the first exposure
#' 
#' @param duration an `integer` indicating the number of days after the last 
#'   exposure a contact should be followed for; usually determined according to 
#'   the incubation time distribution; defaults to 21 days
#'   
#' @param strategy a `character` indicating the follow-up strategy to use in the
#'   simulations; currently available values are: "random"; see details section
#'   for more information
#' 
#' @return `x` with columns `last_visit` and `detection_date` updated according to the follow-up strategy.
#'   
#' @details
#' Available follow-up strategies (`strategy` argument) include:
#' 
#' - "random": individuals are visited at random every day of the simulation
#' 
#' - "geo_random": locations are prioritized at random every day of the 
#'  simulation; as many contacts as possible are visited in the first chosen 
#'  location, then if capacity remains, in the second, third, etc.
#'  
#' - "ctscore": individuals are prioritized by highest ctscore every day of the 
#'   simulation
#'   
#' - "geo_ctscore": geographic locations are prioritized according by highest
#'   ctscore every day of the simulation; as many contacts as possible are 
#'   visited in the first chosen location, then if capacity remains, in the 
#'   second, third, etc.  
#' 
#' @examples
#' sim_ctdata() |> 
#' sim_followup(coverage = 0.2, delay = 7, strategy = "random") |> 
#' plot()
#' 
sim_followup <- function(x, 
                         time = 1, 
                         delay = 1,
                         duration = 21, 
                         coverage = 0, 
                         strategy = c("random", 
                                      "geo_random", 
                                      "ctscore", 
                                      "geo_ctscore")
                         ) {
  
  # Check inputs
  if (!inherits(x, "ctdata")) {
    stop("x must be a ctdata object")
  }
  time <- process_duration(time, "time", strictly_positive = TRUE)
  delay <- process_duration(delay, "delay", strictly_positive = TRUE)
  duration <- process_duration(duration, "duration", strictly_positive = TRUE)
  coverage <- process_proportion(coverage, "coverage")
 
  ## get the corresponding internal sub-routine, named _followup_<strategy>
  f_strategy <- get(paste0("_followup_", strategy))
  out <- f_strategy(
    x, 
    time = time, 
    delay = delay, 
    duration = duration, 
    coverage = coverage
  )

  return(out)
}


