#' Simulate follow-up for contact tracing data
#' 
#' This function adds simulated follow-up to a `ctdata` object as generated by 
#' [make_ctdata()] or simulated via [sim_ctdata()]. The function simulates
#' follow-up for each individual in the `ctdata` object, based on the specified
#' follow-up time and the probability of being followed up. The function returns
#' a modified `ctdata` object with the simulated follow-up data added.
#' 
#' @author Thibaut Jombart
#' 
#' @export
#' 
#' @seealso [make_ctdata()] to create contact tracing data from existing data, 
#' or [sim_ctdata()] to simulate them
#' 
#' @param x a `ctdata` object
#' 
#' @param coverage the proportion of contacts visited at any time step; defaults 
#'   to 0 - no follow-up
#' 
#' @param duration an `integer` indicating the number of days to simulate 
#'   follow-up for; starts from the most recent date in `x`, be it in follow-up 
#'   history or in exposures; defaults to 1 day
#'   
#' @param strategy a `character` indicating the follow-up strategy to use in the
#'   simulations; currently available values are: "random"; see details section
#'   for more information
#'   
#' @details
#' Available follow-up strategies (`strategy` argument) include:
#' 
#' - "random": individuals are visited at random every day of the simulation
#' 
#' - "geo_random": locations are prioritized at random every day of the 
#'  simulation; as many contacts as possible are visited in the first chosen 
#'  location, then if capacity remains, in the second, third, etc.
#'  
#' - "ctscore": individuals are prioritized by highest ctscore every day of the 
#'   simulation
#'   
#' - "geo_ctscore": geographic locations are prioritized according by highest
#'   ctscore every day of the simulation; as many contacts as possible are 
#'   visited in the first chosen location, then if capacity remains, in the 
#'   second, third, etc.  
#' 
sim_followup <- function(x, 
                         duration = 1, 
                         coverage = 0, 
                         strategy = c("random", 
                                      "geo_random", 
                                      "ctscore", 
                                      "geo_ctscore")
                         ) {
  
  # Check inputs
  if (!inherits(x, "ctdata")) {
    stop("x must be a ctdata object")
  }
  stopifnot(is.numeric(duration))
  stopifnot(is.finite(duration))
  stopifnot(duration > 0)
  stopifnot(is.numeric(coverage))
  stopifnot(is.finite(coverage))
  stopifnot(coverage >= 0)
  stopifnot(coverage <= 1)
  strategy <- match.arg(strategy)
  
  f_strategy <- get(paste0("_followup_", strategy))
  out <- f_strategy(x)
  return(out)
}


