#' Simulate follow-up for contact tracing data
#' 
#' This function adds simulated follow-up to a `ctdata` object as generated by 
#' [make_ctdata()] or simulated via [sim_ctdata()]. The function simulates
#' follow-up for each individual in the `ctdata` object, based on the specified
#' follow-up time and the probability of being followed up. The function returns
#' a modified `ctdata` object with the simulated follow-up data added.
#' 
#' @author Thibaut Jombart
#' 
#' @export
#' 
#' @param x a `ctdata` object
#' 
#' @seealso [make_ctdata()] to create contact tracing data from existing data, 
#' or [sim_ctdata()] to simulate them
#' 
sim_followup <- function(x, coverage = 0) {
  
  # Check that ctdata is a valid ctdata object
  if (!inherits(x, "ctdata")) {
    stop("x must be a ctdata object")
  }
  
  out <- x
  return(out)
}


